// ********RoostGPT********
// Test generated by RoostGPT for test roost-test using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
#include <gtest/gtest.h>
#include <assert.h>
#include <limits>
#include <random>
// Include the SortSearch.hpp header which contains the Obtain class.
#include "include/SortSearch.hpp"

// Main function to run all the tests.
int main(int argc, char **argv) {
  ::testing::InitGoogleTest(&argc, argv);
  // Remove all recognized flags.
  // Note: This step may not be necessary if we are not directly handling command line flags.
  return RUN_ALL_TESTS();
}

